# Generated by Django 2.2.6 on 2020-01-27 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpanelledFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=50)),
                ('firm_dilno', models.CharField(blank=True, max_length=50)),
                ('firm_phone', models.CharField(default='0', max_length=10)),
                ('firm_gstno', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthCentreStaff',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_type', models.CharField(choices=[('DR', 'Doctor'), ('PR', 'Pharmacist'), ('ST', 'Other staff'), ('MS', 'Medical Superintendent')], default='DR', max_length=2)),
                ('staff_address', models.TextField()),
                ('availability_from', models.CharField(max_length=4)),
                ('availability_to', models.CharField(max_length=4)),
                ('user_id', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('manufacturing_company', models.CharField(default='XX', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Ointment', 'Ointment'), ('Injection', 'Injection'), ('Solution', 'Solution'), ('Equipment', 'Equipment'), ('Dental', 'Dental'), ('Capsule', 'Capsule'), ('Oil', 'Oil'), ('Powder', 'Powder'), ('Gargle', 'Gargle'), ('Others', 'Others')], default='Tablet', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('isDependant', models.BooleanField()),
                ('doctor_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.HealthCentreStaff')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_serial_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_of_issue', models.DateField()),
                ('complaint', models.CharField(default='Unspecified', max_length=50)),
                ('diagnosis', models.CharField(default='Yet to be announced', max_length=50)),
                ('followup_date', models.DateField(blank=True, default=None, null=True)),
                ('medicine_prescribed', models.BooleanField(default=False)),
                ('tests_recommended', models.BooleanField(default=False)),
                ('patient_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.PatientRecord')),
            ],
        ),
        migrations.CreateModel(
            name='RegularStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('requisition_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_of_order', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_of_approval', models.DateField()),
                ('memo', models.TextField()),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('batch_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('firm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.EmpanelledFirm')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('person_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('medicine_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('expiry_date', models.DateField()),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Stock')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_received', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine')),
                ('requisition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('test_result', models.CharField(max_length=50)),
                ('patient_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.PatientRecord')),
                ('prescription_id', models.ForeignKey(db_column='prescription_serial_number', on_delete=django.db.models.deletion.CASCADE, to='doctor.Prescription')),
            ],
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='patient_id',
            field=models.ForeignKey(db_column='person_id', default='16-1-5-009', on_delete=django.db.models.deletion.CASCADE, to='doctor.StudentRecord'),
        ),
        migrations.CreateModel(
            name='MedicineIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_quantity', models.IntegerField(blank=True, default=0)),
                ('issue_status', models.BooleanField()),
                ('non_issue_reason', models.CharField(blank=True, max_length=50)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.StockMedicine')),
                ('prescription_serial_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCentreStaffContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_phone_no', models.CharField(max_length=10)),
                ('staff_email_id', models.EmailField(blank=True, max_length=254)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.HealthCentreStaff')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('present', models.BooleanField()),
                ('cured', models.BooleanField()),
                ('furthercomments', models.TextField()),
                ('patient_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.PatientRecord')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRequisitionProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('doctor_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.HealthCentreStaff')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine')),
                ('requisition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Requisition')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Requisition')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_ingredient', models.CharField(max_length=50)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine')),
            ],
        ),
    ]
