# Generated by Django 2.2.6 on 2020-01-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bill_date', models.DateField()),
                ('firm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.EmpanelledFirm')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockmedicine',
            name='batch_no',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='stockmedicine',
            name='bill_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doctor.Bill'),
            preserve_default=False,
        ),
    ]
