# Generated by Django 2.2.6 on 2020-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20200128_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
