# Generated by Django 2.2.4 on 2019-09-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_healthcentrestaff_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='prescription_serial_no',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='doctor.Prescription'),
        ),
    ]
