# Generated by Django 2.2.6 on 2020-01-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200128_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
    ]
