# Generated by Django 2.2.4 on 2019-09-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190922_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine_prescribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='tests_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
