# Generated by Django 2.2.4 on 2019-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20190922_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
