# Generated by Django 2.2.4 on 2019-09-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20190901_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='prescription_serial_no',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Prescription'),
        ),
    ]
