# Generated by Django 2.2.5 on 2020-01-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_medicine_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='recommendedtest',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='recommendedtest',
            name='prescription_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_record_id',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_id',
            field=models.ForeignKey(db_column='staff_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.HealthCentreStaff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_id',
            field=models.ForeignKey(db_column='person_id', default='16-1-5-009', on_delete=django.db.models.deletion.CASCADE, to='doctor.StudentRecord'),
        ),
        migrations.DeleteModel(
            name='FollowUpReport',
        ),
        migrations.DeleteModel(
            name='PatientRecord',
        ),
        migrations.DeleteModel(
            name='RecommendedTest',
        ),
    ]
