# Generated by Django 2.2.4 on 2019-09-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20190902_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicineissue',
            old_name='medicine_quantity_issued',
            new_name='medicine_quantity',
        ),
        migrations.RemoveField(
            model_name='medicineissue',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medicineissue',
            name='medicine_quantity_prescribed',
        ),
    ]
