# Generated by Django 2.2.4 on 2019-09-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20190925_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='followup_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
