# Generated by Django 2.2.5 on 2020-01-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20200130_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='tests_recommended',
        ),
    ]
