# Generated by Django 2.2.5 on 2020-01-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20200130_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='nationality',
        ),
    ]
