# Generated by Django 2.2.4 on 2019-09-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Ointment', 'Ointment'), ('Injection', 'Injection'), ('Solution', 'Solution'), ('Equipment', 'Equipment'), ('Dental', 'Dental'), ('Capsule', 'Capsule'), ('Oil', 'Oil'), ('Powder', 'Powder'), ('Gargle', 'Gargle'), ('Others', 'Others')], default='Tablet', max_length=100),
        ),
    ]
