# Generated by Django 2.2.5 on 2020-02-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20200131_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
