# Generated by Django 2.2.4 on 2019-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20190925_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_of_issue',
            field=models.DateField(),
        ),
    ]
