# Generated by Django 2.2.5 on 2019-10-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20190925_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Ointment', 'Ointment'), ('Injection', 'Injection'), ('Solution', 'Solution'), ('Equipment', 'Equipment'), ('Dental', 'Dental'), ('Capsule', 'Capsule'), ('Oil', 'Oil'), ('Powder', 'Powder'), ('Gargle', 'Gargle'), ('Others', 'Others')], default='Tablet', max_length=100),
        ),
    ]
