# Generated by Django 2.2.5 on 2020-02-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_medicine_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
    ]
