# Generated by Django 2.2.6 on 2019-11-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20191014_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineissue',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.StockMedicine'),
        ),
    ]
