# Generated by Django 2.2.4 on 2019-10-31 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20191014_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineissue',
            name='medicine_id',
        ),
    ]
