# Generated by Django 2.2.5 on 2020-02-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20200203_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.RegularStaff'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_id',
            field=models.ForeignKey(db_column='person_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.StudentRecord'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_serial_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
