# Generated by Django 2.2.6 on 2019-11-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20191103_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
