# Generated by Django 2.2.5 on 2020-02-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20200203_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_prescribed',
        ),
    ]
