# Generated by Django 2.2.5 on 2020-02-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_prescription_medicine_prescribed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescription',
            unique_together={('doctor_id', 'prescription_serial_no')},
        ),
    ]
