# Generated by Django 2.2.5 on 2020-02-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20200203_1850'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescription',
            unique_together=set(),
        ),
    ]
