# Generated by Django 2.2.5 on 2020-02-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_auto_20200203_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_serial_no',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
