# Generated by Django 2.2.6 on 2020-02-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_auto_20200206_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineissue',
            name='issue_status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
