# Generated by Django 2.2.6 on 2020-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_auto_20200220_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='isDependent',
            field=models.BooleanField(default=False),
        ),
    ]
