# Generated by Django 2.2.6 on 2020-04-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_regularstaff_staff_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposedmedicine',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='disposedmedicine',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='healthcentrestaffcontact',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='requisitionmedicine',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='requisitionmedicine',
            name='requisition_id',
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
        migrations.DeleteModel(
            name='DisposedMedicine',
        ),
        migrations.DeleteModel(
            name='HealthCentreStaffContact',
        ),
        migrations.DeleteModel(
            name='RequisitionMedicine',
        ),
    ]
