# Generated by Django 2.2.6 on 2020-03-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_auto_20200220_1905'),
        ('doctor', '0021_regularstaff_staff_dept'),
    ]

    operations = [
    ]
